getal1 = int(input("Geef het getal op: "))
getal2 = int(input("Geef het getal op: "))
resultaat = (getal1 + getal2) * (getal1 + getal2)
print(f"Geef een getal op: {getal1}")
print(f"Geef een getal op: {getal2}")
print(f"({getal1} + {getal2}) ^2 = {resultaat}")
